@production = https://backendenlafarma.herokuapp.com/api

@localhost = http://localhost:4002/api

###
GET {{production}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU2NzkxMjEsImV4cCI6MTYwNTcxMTUyMX0.LLnrvhvNlv4M0Ulz27d-8hndC_MXmVK0oKxuqAJWR8I
Content-Type: application/json

###
GET {{production}}/customers/35
Authorization: BearereyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNjlmNjViNS00YWI1LTQ5YTMtOWVkMC1jNzExMDJlZTkyNDkiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoyLCJpYXQiOjE2MDU1MTI2NTgsImV4cCI6MTYwNTU0NTA1OH0.OYqqe4g0CJRs1O7myPxUAZcyrSZ1r5PpT4KXLdz1JCo
Content-Type: application/json

###
GET {{localhost}}/customers/branch/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU2ODMwMzIsImV4cCI6MTYwNTcxNTQzMn0.9PA7NELRFDFBlLk21ht322Ks5fq7whB-5ZtYDE6u45U
Content-Type: application/json

###
POST {{production}}/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU2ODMwMzIsImV4cCI6MTYwNTcxNTQzMn0.9PA7NELRFDFBlLk21ht322Ks5fq7whB-5ZtYDE6u45U
Content-Type: application/json

{
    "name":"María Nájera",
    "address":"Sansare, Jalapa",
    "nit":"123456789",
    "contact":"Luis cisneros",
    "phone":"1231353",
    "branch_idbranch":"3"
}


