@hostdev = http://localhost:4002/api

###
GET {{hostdev}}/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3MzUyNjEsImV4cCI6MTYwNTc2NzY2MX0.gfqupK2B1tnmEYI08aS4xMhPK25pEOFNShJWOHzMkT8
Content-Type: application/json

###
POST {{hostdev}}/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3MzUyNjEsImV4cCI6MTYwNTc2NzY2MX0.gfqupK2B1tnmEYI08aS4xMhPK25pEOFNShJWOHzMkT8
Content-Type: application/json

{
    "name": "Ciprofloxacina"
}