@hostdev = http://localhost:4002/api
@production = https://backendenlafarma.herokuapp.com/api
###
POST {{hostdev}}/sales
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3NDYxODQsImV4cCI6MTYwNTc3ODU4NH0.9thi2Dy2LIxhk13fwETiG4994-NVive5g7SOW4_Uph4
Content-Type: application/json

{
    "data": [
        {
       "customer_idcustomer": 30,
       "price": 35,
       "quantity": 10,
       "total": 350,
       "product_idproduct": 4
   },
   {
       "customer_idcustomer": 30,
       "price": 10,
       "quantity": 10,
       "total": 100,
       "product_idproduct": 3
   }
    ]
}

###
GET {{hostdev}}/customers/sale/30
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3NDYxODQsImV4cCI6MTYwNTc3ODU4NH0.9thi2Dy2LIxhk13fwETiG4994-NVive5g7SOW4_Uph4