@hostdev = http://localhost:4002/api
@production = https://backendenlafarma.herokuapp.com/api
###
POST {{production}}/sales
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3MzU2MzEsImV4cCI6MTYwNTc2ODAzMX0.L6usIn9uRC3RvhYk4TJd2etVxve80ZlkuS_PfyRTM_0
Content-Type: application/json

{
    "data": [
        {
       "customer_idcustomer": 30,
       "price": 35,
       "quantity": 10,
       "total": 350,
       "product_idproduct": 4
   },
   {
       "customer_idcustomer": 30,
       "price": 10,
       "quantity": 10,
       "total": 100,
       "product_idproduct": 3
   }
    ]
}

###
GET {{production}}/customers/sale/30
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MWE0OTAwOC1hZjA0LTRlZmItOTY2Zi1hY2JjMjZhZDU0MWUiLCJyb2wiOiJhZG1pbiIsImlkdmVuZG9yIjoxLCJpYXQiOjE2MDU3MzU2MzEsImV4cCI6MTYwNTc2ODAzMX0.L6usIn9uRC3RvhYk4TJd2etVxve80ZlkuS_PfyRTM_0